// <auto-generated />
using System;
using CourseService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseService.Api.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    partial class CourseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseService.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Students")
                        .HasColumnType("int");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Graphic Design",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn machine learning basics",
                            Duration = "6 weeks",
                            Image = "/images/course1.jpg",
                            Instructor = "Jennifer Anderson",
                            Level = "Beginner",
                            Rating = 5.0,
                            Students = 120,
                            StudyProgramId = 0,
                            Title = "Machine Learning Basics"
                        },
                        new
                        {
                            Id = 2,
                            Category = "UI/UX Design",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business analytics course",
                            Duration = "8 weeks",
                            Image = "/images/course2.jpg",
                            Instructor = "Robert Chen",
                            Level = "Intermediate",
                            Rating = 5.0,
                            Students = 95,
                            StudyProgramId = 0,
                            Title = "Business Analytics & Strategy"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Brand Identity",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Marketing fundamentals",
                            Duration = "5 weeks",
                            Image = "/images/course3.jpg",
                            Instructor = "Emily Davis",
                            Level = "Beginner",
                            Rating = 5.0,
                            Students = 70,
                            StudyProgramId = 0,
                            Title = "Content Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Web Design",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Product design basics",
                            Duration = "7 weeks",
                            Image = "/images/course4.jpg",
                            Instructor = "Michael Torres",
                            Level = "Beginner",
                            Rating = 5.0,
                            Students = 110,
                            StudyProgramId = 0,
                            Title = "Product Design for Beginner"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Development",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Backend development course",
                            Duration = "10 weeks",
                            Image = "/images/course5.jpg",
                            Instructor = "Sarah Williams",
                            Level = "Intermediate",
                            Rating = 4.0,
                            Students = 150,
                            StudyProgramId = 0,
                            Title = "Backend Developer"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Design",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adobe XD design course",
                            Duration = "4 weeks",
                            Image = "/images/course6.jpg",
                            Instructor = "David Martinez",
                            Level = "Beginner",
                            Rating = 5.0,
                            Students = 60,
                            StudyProgramId = 0,
                            Title = "Adobe XD for Designer"
                        });
                });

            modelBuilder.Entity("CourseService.Api.Models.StudyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyPrograms");
                });

            modelBuilder.Entity("CourseService.Api.Models.Course", b =>
                {
                    b.HasOne("CourseService.Api.Models.StudyProgram", "StudyProgram")
                        .WithMany("Courses")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("CourseService.Api.Models.StudyProgram", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
